apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app-deployment
spec:
  selector:
    matchLabels:
      app: employee-app-deployment
  replicas: 3 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: employee-app-deployment
    spec:
      containers:
        - name: employee-app-deployment
          image: employee-app:1.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090 # The port that the container is running on in the cluster